In [1]:
import pandas as pd

# Define the paths to your CSV files
csv_files = [
    '/Users/joaquincasasus/Desktop/TFG/2/1_1998-11-20 to 1999-05-17.csv',
    '/Users/joaquincasasus/Desktop/TFG/2/2_1999-11-18 to 2000-05-09.csv',
    '/Users/joaquincasasus/Desktop/TFG/2/3_2000-11-14 to 2001-05-12.csv',
    '/Users/joaquincasasus/Desktop/TFG/2/4_2001-11-23 to 2002-05-13.csv',
    '/Users/joaquincasasus/Desktop/TFG/2/5_2002-11-15 to 2003-05-05.csv',
    '/Users/joaquincasasus/Desktop/TFG/2/6_2003-11-01 to 2004-05-25.csv',
    '/Users/joaquincasasus/Desktop/TFG/2/7_2004-11-30 to 2005-05-09.csv',
    '/Users/joaquincasasus/Desktop/TFG/2/8_2005-12-03 to 2006-05-12.csv',
    '/Users/joaquincasasus/Desktop/TFG/2/9_2006-12-09 to 2007-04-23.csv',
    '/Users/joaquincasasus/Desktop/TFG/2/10_2007-11-13 to 2008-05-14.csv',
    '/Users/joaquincasasus/Desktop/TFG/2/11_2008-10-29 to 2009-05-18.csv',
    '/Users/joaquincasasus/Desktop/TFG/2/12_2009-11-28 to 2010-05-17.csv',
    '/Users/joaquincasasus/Desktop/TFG/2/13_2010-11-26 to 2011-05-02.csv',
    '/Users/joaquincasasus/Desktop/TFG/2/14_2011-12-08 to 2012-05-07.csv',
    '/Users/joaquincasasus/Desktop/TFG/2/15_2012-11-02 to 2013-05-06.csv',
    '/Users/joaquincasasus/Desktop/TFG/2/16_2013-11-29 to 2014-05-04.csv',
    '/Users/joaquincasasus/Desktop/TFG/2/17_2014-11-09 to 2015-05-04.csv',
    '/Users/joaquincasasus/Desktop/TFG/2/18_2015-11-21 to 2016-05-09.csv',
    '/Users/joaquincasasus/Desktop/TFG/2/19_2016-11-10 to 2017-05-09.csv',
    '/Users/joaquincasasus/Desktop/TFG/2/20_2017-11-12 to 2018-05-07.csv',
    '/Users/joaquincasasus/Desktop/TFG/2/21_2018-11-02 to 2019-05-21.csv'

]

# Read each CSV file and store them in a list
dfs = [pd.read_csv(file) for file in csv_files]

# Concatenate all DataFrames in the list one below the other
concatenated_df = pd.concat(dfs, ignore_index=True)

# If you want to save the concatenated DataFrame to a new CSV file
concatenated_df.to_csv('/Users/joaquincasasus/Desktop/TFG/2/concatenated_file.csv', index=False)

In [2]:
import pandas as pd

# Define the paths to your CSV files
csv_files = [
    '/Users/joaquincasasus/Desktop/TFG/2/1_1998-11-20 to 1999-05-17.csv',
    '/Users/joaquincasasus/Desktop/TFG/2/2_1999-11-18 to 2000-05-09.csv',
    '/Users/joaquincasasus/Desktop/TFG/2/3_2000-11-14 to 2001-05-12.csv',
    '/Users/joaquincasasus/Desktop/TFG/2/4_2001-11-23 to 2002-05-13.csv',
    '/Users/joaquincasasus/Desktop/TFG/2/5_2002-11-15 to 2003-05-05.csv'
]

# Loop through each file, read it, and print its shape
for file in csv_files:
    df = pd.read_csv(file)
    print(f'Shape of {file}: {df.shape}')

Shape of /Users/joaquincasasus/Desktop/TFG/2/1_1998-11-20 to 1999-05-17.csv: (179, 33)
Shape of /Users/joaquincasasus/Desktop/TFG/2/2_1999-11-18 to 2000-05-09.csv: (174, 33)
Shape of /Users/joaquincasasus/Desktop/TFG/2/3_2000-11-14 to 2001-05-12.csv: (180, 33)
Shape of /Users/joaquincasasus/Desktop/TFG/2/4_2001-11-23 to 2002-05-13.csv: (172, 33)
Shape of /Users/joaquincasasus/Desktop/TFG/2/5_2002-11-15 to 2003-05-05.csv: (172, 33)

In [5]:
import pandas as pd

# Replace 'file_path.csv' with the path to your CSV file
file_path = 'file_path.csv'

# Read the CSV file into a pandas DataFrame
df = pd.read_csv("/Users/joaquincasasus/Desktop/TFG/2/concatenated_file.csv")
df2 = pd.read_csv("/Users/joaquincasasus/Desktop/TFG/2/data_set_1_avalanche_observations_wi9899_to_wi1819_davos.csv")

In [17]:
df.head()

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,solarenergy,uvindex,severerisk,sunrise,sunset,moonphase,conditions,description,icon,stations
0,"Davos, Graubünden, Schweiz",1998-11-20,-4.9,-10.1,-7.7,-10.2,-16.5,-13.7,-14.2,61.4,...,NaN,NaN,NaN,1998-11-20T07:30:06,1998-11-20T16:42:02,0.04,"Snow, Partially cloudy",Partly cloudy throughout the day with snow.,snow,"11110099999,06990099999,06680099999,0678609999..."
1,"Davos, Graubünden, Schweiz",1998-11-21,-5.3,-12.9,-9.3,-11.5,-19.5,-16.6,-16.6,56.1,...,NaN,NaN,NaN,1998-11-21T07:31:30,1998-11-21T16:41:08,0.08,"Snow, Partially cloudy",Partly cloudy throughout the day with afternoo...,snow,"06990099999,06786099999,06794099999,0679209999..."
2,"Davos, Graubünden, Schweiz",1998-11-22,-5.9,-13.4,-9.6,-5.9,-21.4,-13.2,-14.5,68.3,...,NaN,NaN,NaN,1998-11-22T07:32:53,1998-11-22T16:40:17,0.11,"Snow, Partially cloudy",Partly cloudy throughout the day with afternoo...,snow,"06990099999,06786099999,06792099999,1110509999..."
3,"Davos, Graubünden, Schweiz",1998-11-23,0.1,-9.4,-4.1,-1.9,-12.2,-6.5,-10.3,63.4,...,NaN,NaN,NaN,1998-11-23T07:34:16,1998-11-23T16:39:28,0.15,"Snow, Partially cloudy",Partly cloudy throughout the day with afternoo...,rain,"11110099999,06990099999,06786099999,1110109999..."
4,"Davos, Graubünden, Schweiz",1998-11-24,0.1,-4.8,-2.1,-2.9,-9.3,-5.7,-5.6,77.6,...,NaN,NaN,NaN,1998-11-24T07:35:37,1998-11-24T16:38:42,0.18,"Snow, Partially cloudy",Partly cloudy throughout the day with early mo...,rain,"11110099999,06990099999,06786099999,0679209999..."

In [16]:
df2.head()

  no;date_release;snow_type;trigger_type;max_elevation_m;min_elevation_m;aspect_degrees;length_m;width_m;perimeter_length_m;area_m2;aval_size_class;weight_AAI;max.danger.corr
0  1;1998-11-06;dry;NATURAL;2476;2439;4;63;33;168...
1  2;1998-12-07;dry;NATURAL;2562;2484;42;101;123;...
2  3;1998-12-07;dry;NATURAL;2494;2356;21;127;351;...
3  4;1998-12-07;dry;HUMAN;2115;2017;200;166;85;45...
4  5;1998-12-07;dry;NATURAL;2085;1986;42;128;18;2...